# Generated by Django 3.0.5 on 2021-03-18 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IQBoardDurum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durum', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IQBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=60)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, help_text='Opsiyonel')),
                ('durum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.IQBoardDurum')),
            ],
        ),
    ]
