# Generated by Django 2.2.5 on 2021-03-15 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IQCardDurumlari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durum', models.TextField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IQCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metin', models.TextField(help_text='Kartı tanımlayın', max_length=150)),
                ('icerik', models.TextField(help_text='Kart icerigi', max_length=250)),
                ('pl_baslangic', models.DateTimeField(help_text='Planlanan başlama tarihi')),
                ('pl_bitis', models.DateTimeField(help_text='Planlanan bitiş tarihi')),
                ('atanmis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atanmis', to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.IQBoard')),
                ('durum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.IQCardDurumlari')),
                ('sahip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sahip', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
